[package]
id = custom_viz_horizon_chart
check_for_updates = 0

[id]
version = 1.1.4
name = custom_viz_horizon_chart

[ui]
is_visible = 1
label = Horizon Chart
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A horizon chart that folds many time series into compact color bands, for Splunk Dashboard Studio
version = 1.1.4

[install]
is_configured = 0
build = <@- buildNumber @>
