[id]
name = ops_console
version = 1.0.0

[ui]
is_visible = 1
label = Ops Console
supported_themes = light,dark

[launcher]
author = custom-viz
description = Splunk 上で動く独立 React アプリ（Splunk App with React）の実証
version = 1.0.0

[package]
check_for_updates = 0
id = ops_console

[install]
is_configured = 1
build = 1
