[package]
id = custom_viz_spotlight_frame
check_for_updates = 0

[id]
version = 1.2.3
name = custom_viz_spotlight_frame

[ui]
is_visible = 1
label = Spotlight Frame
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A data-driven status frame (colored border, glow and header badge) that reacts to a status/severity value for Splunk Dashboard Studio
version = 1.2.3

[install]
is_configured = 0
build = <@- buildNumber @>
