[package]
id = custom_viz_donut_graph
check_for_updates = 0

[id]
version = 1.1.3
name = custom_viz_donut_graph

[ui]
is_visible = 1
label = Donut Graph
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A custom visualization for Splunk Dashboard Studio
version = 1.1.3

[install]
is_configured = 0
build = <@- buildNumber @>
