[package]
id = custom_viz_waterfall_chart
check_for_updates = 0

[id]
version = 1.0.0
name = custom_viz_waterfall_chart

[ui]
is_visible = 1
label = Custom Viz Waterfall Chart
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A waterfall (bridge) chart showing how sequential increases and decreases build up to a total, for Splunk Dashboard Studio
version = 1.0.0

[install]
is_configured = 0
build = <@- buildNumber @>
