[package]
id = custom_viz_network_graph
check_for_updates = 0

[id]
version = 1.0.1
name = custom_viz_network_graph

[ui]
is_visible = 1
label = Custom Viz Network Graph
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A physics-based force-directed network graph for Splunk Dashboard Studio
version = 1.0.1

[install]
is_configured = 0
build = <@- buildNumber @>
