[package]
id = custom_viz_worldmap
check_for_updates = 0

[id]
version = 1.0.0
name = custom_viz_worldmap

[ui]
is_visible = 1
label = Custom Viz Worldmap
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A custom visualization for Splunk Dashboard Studio
version = 1.0.0

[install]
is_configured = 0
build = <@- buildNumber @>
