[package]
id = custom_viz_metric_terrain
check_for_updates = 0

[id]
version = 1.1.4
name = custom_viz_metric_terrain

[ui]
is_visible = 1
label = Metric Terrain
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A custom visualization for Splunk Dashboard Studio
version = 1.1.4

[install]
is_configured = 0
build = <@- buildNumber @>
