[package]
id = custom_viz_calendar_heatmap

[id]
version = 0.7.2
name = custom_viz_calendar_heatmap

[ui]
is_visible = 1
label = Custom Viz Calendar Heatmap
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = A custom visualization for Splunk Dashboard Studio
version = 0.7.2

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
