[package]
id = custom_viz_chord_flow
check_for_updates = 0

[id]
version = 1.0.0
name = custom_viz_chord_flow

[ui]
is_visible = 1
label = Custom Viz Chord Flow
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = An animated chord diagram with directional flow particles for Splunk Dashboard Studio
version = 1.0.0

[install]
is_configured = 0
build = <@- buildNumber @>
