[package]
id = custom_viz_link_line
check_for_updates = 0

[id]
version = 1.5.0
name = custom_viz_link_line

[ui]
is_visible = 1
label = Custom Viz Link Line
show_in_nav = 0

[launcher]
author = Yuto Ishitsuki
description = An editable connector line between servers with value-based threshold colors for Splunk Dashboard Studio (SOC topology link)
version = 1.5.0

[install]
is_configured = 0
build = <@- buildNumber @>
