[package]
id = custom_viz_liquid_tube

[id]
version = 1.0.2
name = custom_viz_liquid_tube

[ui]
is_visible = 1
label = Liquid Tube
show_in_nav = 0

[launcher]
author = Unknown
description = 試験管型の液体ゲージ（WebGL）
version = 1.0.2

[install]
is_configured = 0
build = <@- buildNumber @>
check_for_updates = 0

[manifest]
category = Custom
